//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel; // Pentru a folosi DisplayName,
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserID { get; set; }


        [DisplayName("User Name")] // in Index se afiseaza "User Name" in loc de "UserName"
        [Required(ErrorMessage="This field is required.")]

        public string UserName { get; set; }


        [DataType(DataType.Password)] // se afiseaza format parola
        [Required(ErrorMessage="This field is required.")] // validator
        public string Password { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
